[tool.poetry]
name = "merkly"
version = "0.5.2"
description = "ðŸŒ³ The simple and easy implementation of Merkle Tree"
authors = ["Lucas Oliveira <olivmath@protonmail.com>"]
repository = "https://github.com/olivmath/merkly.git"
documentation = "https://pypi.org/project/merkly/"
readme = "README.md"
license = "MIT"
keywords = [
  "merkle-tree",
  "merkle-proof",
  "merkle-root",
  "keccak256",
  "blockchain"
]

[tool.poetry.dependencies]
python = "^3.7.2"
pysha3 = "^1.0.2"
pylint = "^2.14.5"
pydantic = "^1.10.2"
rich = ">=12.6,<14.0" # for beatfull print 
pytest-watcher = "^0.2.3"

[tool.poetry.group.dev.dependencies]
pytest = "^7.1.2"
flake8 = "^5.0.4"
autopep8 = "^1.7.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
w-t = "scripts.poetry:w_t"
lint = "scripts.poetry:lint"